//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICE()
        {
            this.INVOICE_ITEMS = new HashSet<INVOICE_ITEMS>();
        }
    
        public int Id { get; set; }
        public int CUSTOMER_ID { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public decimal INVOICE_TOTAL { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE_ITEMS> INVOICE_ITEMS { get; set; }
    }
}
