//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_ITEMS
    {
        public int Id { get; set; }
        public int INVOICE_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int QUANTITY { get; set; }
        public decimal TOTAL_PRICE { get; set; }
        public Nullable<decimal> discount { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
