//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_ENTRY
    {
        public int Id { get; set; }
        public int PRODUCT_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
        public int QUANTITY { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
